Repository rh-ecosystem-edge/assisted-chat, pull requests merged in 2025-08, with the labels that each got.

#80 MGMT-21271: Add more workers
  template.yaml
Labels: approved, lgtm

#86 Change misleading echo
  scripts/run.sh
Labels: approved

#98 MGMT-21239: creating an image which could be started in the cluster claimed by prow
  test/prow/Dockerfile
Labels: approved, lgtm, ok-to-test

#99 Add me (keitwb) as repo reviewer
  OWNERS
Labels: approved, lgtm, ok-to-test

#103 Add litellm proxy extra
  Containerfile.add_llama_to_lightspeed
  Containerfile.assisted-chat
Labels: approved, lgtm

#105 Use sqlite for metadata store
  config/llama_stack_client_config.yaml
  template.yaml
Labels: approved, lgtm

#107 pin litellm to 1.75.3
  Containerfile.add_llama_to_lightspeed
  Containerfile.assisted-chat
Labels: approved, lgtm

#109 MGMT-21239: creating an image which could be started in the cluster claimed by prow
  test/evals/eval.py
  test/prow/Dockerfile
  test/prow/entrypoint.sh
  test/prow/template.yaml
  test/prow/template_patch.diff
Labels: approved, lgtm, ok-to-test

#90 Generate lightspeed-stack.yaml from template.yaml
  .gitignore
  lightspeed-stack.template.yaml
  scripts/generate.sh
  template-params.dev.env
  template.yaml
Labels: approved, lgtm, ok-to-test

#78 Insights Export Config
  template.yaml
Labels: approved, lgtm, ok-to-test

#112 Use lightspeed-core official image for exporter
  template.yaml
Labels: approved, lgtm

#113 Use new names for the lightspeed data export flags
  template-params.dev.env
Labels: approved, lgtm

#114 add instruction to obtain information from conversation context
  template.yaml
Labels: approved, lgtm

#115 update the patch file of template.yaml to be compatible with the latest changes
  test/prow/template_patch.diff
Labels: approved, lgtm, ok-to-test

#120 Add Makefile targets to query different environments
  Makefile
  scripts/query.sh
Labels: approved, lgtm

#118 add ServiceAccount to openshift template
  template.yaml
Labels: approved, lgtm

#127 MGMT-21442: Update AI system prompt to provide additional usage guidance
  template.yaml
Labels: approved, lgtm, ok-to-test

#117 eval: data model change for multi-eval
  test/evals/eval.py
  test/evals/eval_data.yaml
Labels: approved, lgtm

#129 MGMT-21239: moving the deploy script of assisted-chat to the repository
  Makefile
  scripts/deploy_template.sh
  test/prow/Dockerfile
  test/prow/entrypoint.sh
  test/prow/template.yaml
Labels: approved, lgtm

#143 Restore `ligthspeed-to-dataverse-exporter`
  template.yaml
Labels: approved, lgtm

#145 disable postgress ssl for local dev
  template-params.dev.env
Labels: approved, lgtm

#154 MGMT-21349: not using the term 'installer-managed networking'
  template.yaml
Labels: approved, lgtm

#142 MGMT-20906: Re-enabling the evaluation tests. The eval test does not need to run in an openshift deployment
  scripts/ci_test.sh
  scripts/deploy_template.sh
  test/evals/eval.py
  test/prow/entrypoint.sh
  test/prow/template.yaml
Labels: approved

#156 Update system prompt in the template
  template.yaml
Labels: approved, lgtm

#159 Remove RBAC from config
  template.yaml
Labels: approved, lgtm

#166 env-sub llama-stack patch
  Containerfile.add_llama_to_lightspeed
  Containerfile.assisted-chat
Labels: approved

#158 Dynamic image/tag resolution for deployments and automatic detection of the current managed service pod
  scripts/ci_test.sh
  scripts/deploy_template.sh
Labels: approved, lgtm
