Repository rh-ecosystem-edge/assisted-chat, pull requests merged in 2025-09, with the labels that each got.

#179 no need for getting the exit status of the pod when the logs are being colletcted
  scripts/ci_test.sh
Labels: approved, lgtm

#173 MGMT-21352: Update system prompt regarding static networking support
  assisted-chat-pod.yaml
  scripts/generate.sh
  template.yaml
  test/evals/eval_data.yaml
Labels: approved, lgtm

#174 MGMT-21661: Tooling for Archive Data
  Makefile
  scripts/archives/.gitignore
  scripts/archives/README.md
  scripts/archives/download-and-extract
  scripts/archives/summarize-transcripts
Labels: approved, lgtm

#184 MGMT-21645: clarifying support scope
  template.yaml
  test/evals/eval_data.yaml
Labels: approved, lgtm

#197 add random job id to eval tests template
  test/prow/template.yaml
Labels: approved, lgtm

#199 fix location of ocm_token in test entry point
  test/prow/entrypoint.sh
Labels: approved, lgtm

#202 Removing the openshift version and the base domain from the expected response
  test/evals/eval_data.yaml
Labels: do-not-merge/hold

#204 fix: correct pod selection and job monitoring in Prow tests
  scripts/ci_test.sh
Labels: approved

#205 Fix(test): Update evaluation data
  test/evals/eval_data.yaml
  test/prow/entrypoint.sh
Labels: approved, lgtm

#206 Output eval tests results in case of failure
  scripts/ci_test.sh
Labels: approved, lgtm

#213 making the evaluation tests more stable
  Makefile
  assisted-chat-pod.yaml
  scripts/eval_k8s.sh
  template.yaml
  test/evals/eval.py
  test/evals/eval_data.yaml
  test/prow/Dockerfile
  test/prow/entrypoint.sh
  test/prow/template.yaml
  test/scripts/cluster_create_test_setup.sh
  test/scripts/cluster_created_check.sh
  test/scripts/delete_cluster.sh
Labels: approved, lgtm
